name: Push
on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-push
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/mokmok-dev/gcloud-pubsub-push-emulator
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}}
            type=sha,format=short,prefix=
      - name: Login GitHub Packages
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
