name: Release
on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-release
  cancel-in-progress: true
jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
